version: '1.0'
name: 'react-app'

services:
  client:
    build: 
      context: client
    ports:
      - 3000:3000
    volumes:
      - node:/usr/src/app/node_modules
    restart: always

volumes:
  node:
    external: false